version: '3.8'

services:
  postgres:
    image: postgres:14  # You can use any version you prefer
    environment:
      POSTGRES_USER: postgres          # Custom database user
      POSTGRES_PASSWORD: 12  # Custom user password
      POSTGRES_DB: test       # Custom database name
    ports:
      - "5432:5432"                  # Expose the PostgreSQL port
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist data across container restarts
    networks:
      - mynetwork
      - es-network                   # Network for PostgreSQL
    restart: always

networks:
  mynetwork:
    driver: bridge
  es-network:
    name: es-network
    external: true                     # Use the default bridge network driver

volumes:
  postgres_data:
    driver: local
