version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
      - ./media:/media
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:12@postgres:5432/test
      - PGB_URL=postgresql://postgres:12@pgbouncer:6432/test
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - pgbouncer
      - elasticsearch
      - kibana
    networks:
      - appnet
    restart: always
    command: >
      /wait-for-it.sh elasticsearch:9200 -- 
      /wait-for-it.sh pgbouncer:6432 -- 
      flask db upgrade --quiet && 
      python app.py --host=0.0.0.0 --port=5002

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: 12
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - postgres
    networks:
      - appnet
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch_course
    hostname: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - appnet
    restart: always
    mem_limit: 4g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana_course
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - appnet

volumes:
  postgres_data:
  es-data:

networks:
  appnet:
    driver: bridge
